### PR TITLE
Removed warnings when using rust 1.7.0

### PR DESCRIPTION
**Pull request by stefandisch**
Dear Ralf,

thanks a lot for your tutorial. When using rustic 1.7.0 i got some warnings.
This pull request fixes them.

Best
Stefan

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks! Could you also change `main.rs` and update the minimal required Rust version from 1.2 to 1.3? (According to the docs, that's when the `Duration` type was added.)

**Comment by stefandisch** [comment]
Changed the version in the comments of src/main.rs.

**Comment by RalfJung** [comment]
Great, thank you :)

**Comment by RalfJung** [comment]
Oh, I just noticed you edited the (auto-generated) files in `workspace` instead of the actual source files in `src/´. I will have to re-do that. Sorry for not noticing earlier...

**Comment by stefandisch** [comment]
Sorry, I overlooked that.

**Pull request merged**
