### PR TITLE
Fix potential invalid memory reference.

### PR DESCRIPTION
**Pull request by TorstenScheck**
In order to reveal the bug
* suitable unit tests for iter_mut were added
* and DoubleEndedIterator for IterMut was implemented.

### CODE REVIEW

**Comment by RalfJung** [comment]
Good catch, thanks!

I am wondering however how this is related to having double-ended iterators? I'd prefer to see one commit to do nothing but test and fix this bug (in the existing list), to make it crystal clear what the problem is. Another commit can the add double-ended iterators, fur the fun of it.

I can do that split, but that would probably destroy commit authorship -- so it'd be more appropriate for you to do it.

**Comment by TorstenScheck** [comment]
The dangling pointer which is not set to null in pop_front(), will only be used by iterating from back to front. And for calling iter_mut().rev() in  test_iter_mut() I had to implement double-ended iterators.

I could have used asserts instead of writing tests, but that felt a bit like cheating.

I can still split this into two commits: the fix, and the regression tests. I can also add some explanations, so the unit tests make more sense.

**Comment by RalfJung** [comment]
I am getting a segfault without double-ended iterators:
```rust
    #[test]
    fn test_iter_mut() {
       let mut l = LinkedList::<i32>::new();
        for i in 0..5 {
            l.push_back(i);
        }

        assert_eq!(l.pop_front(), Some(0));
        assert_eq!(l.pop_back(), Some(4));

        for (n, i) in l.iter_mut().enumerate() {
            *i-=1;
            assert_eq!(n as i32, *i);
        }
    }
```

**Comment by TorstenScheck** [comment]
The regular iterator catches the dangling pointer caused by pop_back().
The reverse iterator catches the one caused by pop_front().
So, if you fix only pop_back() and keep pop_front() as it is, your unit test would pass, thus missing the bug in pop_front().

In fact, the reverse iterator might not segfault on the buggy pop_front(). It might wrongly return the contents of the previously popped node, as the structure is most likely still accessible on the heap. But still, the unit test would catch that.

**Comment by TorstenScheck** [comment]
Oops, I re-checked the current test and found that the current implementation of the double ended iterator doesn't trigger the segfault, indeed.

I added the check to avoid crossing next() and next_back() later and thus accidentally prevented the bug to segfault, I guess.

I'll check again how to make the unit test catching the bug reproducibly. I will also create separate commits, as you suggested.

**Comment by TorstenScheck** [comment]
So, I found a way to make the unit test fail.

The next/next_back cross check of next_back() needs to be symmetrical with the one in next(), so self.next_back will be dereferenced. And then pop_front() needs to reset the pointers to zero before dropping the node.

But all this might be too confusing for the users of your tutorial.
I guess, it's really better to just fix the bugs and add another commit with the simple iterator as unit test.

Thanks for your diligence.

**Comment by TorstenScheck** [comment]
I'll another new PR.

**Comment by RalfJung** [comment]
Sorry for the silence, I've had a busy week followed by the need to have a relaxing weekend. I'll look at your new PRs.

Thanks a lot for reworking this!

**Pull request closed without merging**
